### ISSUE TITLE
Unsuccessful TensorSliceReader constructor

### ISSUE THREAD

**Issue by YunchaoLiu** [connorcoley/rexgen_direct#19]
Hello, I'm trying to reproduce the result so I'm trying to run 

`python nntest_direct.py --test ../data/valid.txt.proc --hidden 300 --depth 3 --model mode    l-300-3-direct --checkpoint ckpt-140000`

However, I encountered an error like this:

> 2020-12-20 17:17:36.913461: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2020-12-20 17:17:36.913555: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2020-12-20 17:17:36.913582: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2020-12-20 17:17:36.913606: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2020-12-20 17:17:36.913631: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX512F instructions, but these are available on your machine and could speed up CPU computations.
2020-12-20 17:17:36.913657: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Model size: 757K
2020-12-20 17:17:37.134018: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on mode/model.ckpt-140000: Not found: mode
2020-12-20 17:17:37.134021: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on mode/model.ckpt-140000: Not found: mode
2020-12-20 17:17:37.134061: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on mode/model.ckpt-140000: Not found: mode
2020-12-20 17:17:37.134090: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on mode/model.ckpt-140000: Not found: mode
2020-12-20 17:17:37.134124: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on mode/model.ckpt-140000: Not found: mode
2020-12-20 17:17:37.134183: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on mode/model.ckpt-140000: Not found: mode
2020-12-20 17:17:37.134222: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on mode/model.ckpt-140000: Not found: mode
2020-12-20 17:17:37.134257: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on mode/model.ckpt-140000: Not found: mode
2020-12-20 17:17:37.134315: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on mode/model.ckpt-140000: Not found: mode
2020-12-20 17:17:37.134346: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on mode/model.ckpt-140000: Not found: mode
2020-12-20 17:17:37.134379: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on mode/model.ckpt-140000: Not found: mode
2020-12-20 17:17:37.134413: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on mode/model.ckpt-140000: Not found: mode
2020-12-20 17:17:37.134448: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on mode/model.ckpt-140000: Not found: mode
2020-12-20 17:17:37.134484: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on mode/model.ckpt-140000: Not found: mode
2020-12-20 17:17:37.134534: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on mode/model.ckpt-140000: Not found: mode
2020-12-20 17:17:37.134569: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on mode/model.ckpt-140000: Not found: mode
2020-12-20 17:17:37.134562: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on mode/model.ckpt-140000: Not found: mode
2020-12-20 17:17:37.134563: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on mode/model.ckpt-140000: Not found: mode
2020-12-20 17:17:37.134600: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on mode/model.ckpt-140000: Not found: mode
Traceback (most recent call last):
  File "nntest_direct.py", line 121, in <module>
    saver.restore(session, restore_path)
  File "/home/liuy69/bin/anaconda2/envs/connor_rexgen/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1560, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/liuy69/bin/anaconda2/envs/connor_rexgen/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/liuy69/bin/anaconda2/envs/connor_rexgen/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/liuy69/bin/anaconda2/envs/connor_rexgen/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/liuy69/bin/anaconda2/envs/connor_rexgen/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on mode/model.ckpt-140000: Not found: mode
         [[Node: save/RestoreV2_8 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_8/tensor_names, save/RestoreV2_8/shape_and_slices)]]

>Caused by op u'save/RestoreV2_8', defined at:
  File "nntest_direct.py", line 116, in <module>
    saver = tf.train.Saver()
  File "/home/liuy69/bin/anaconda2/envs/connor_rexgen/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1140, in __init__
    self.build()
  File "/home/liuy69/bin/anaconda2/envs/connor_rexgen/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1172, in build
    filename=self._filename)
  File "/home/liuy69/bin/anaconda2/envs/connor_rexgen/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 688, in build
    restore_sequentially, reshape)
  File "/home/liuy69/bin/anaconda2/envs/connor_rexgen/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/liuy69/bin/anaconda2/envs/connor_rexgen/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/liuy69/bin/anaconda2/envs/connor_rexgen/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 663, in restore_v2
    dtypes=dtypes, name=name)
  File "/home/liuy69/bin/anaconda2/envs/connor_rexgen/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/liuy69/bin/anaconda2/envs/connor_rexgen/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/liuy69/bin/anaconda2/envs/connor_rexgen/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

>InvalidArgumentError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to get matching files on mode/model.ckpt-140000: Not found: mode
         [[Node: save/RestoreV2_8 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_8/tensor_names, save/RestoreV2_8/shape_and_slices)]]

Can someone help me and take a look at this error?

**Comment by YunchaoLiu** [comment]
nvm. It was solved.
